### ISSUE TITLE
Source code does not match crates.io release

### ISSUE THREAD

**Issue by hug-dev** [BusyJay/boringssl-src-rs#1]
Hello 👋!

I had a weird bug in my code:

```
   Compiling boringssl-src v0.3.0+688fc5c
error[E0599]: no method named `get_profile` found for struct `Config` in the current scope
  --> /home/hugdev01/.cargo/registry/src/github.com-1ecc6299db9ec823/boringssl-src-0.3.0+688fc5c/src/lib.rs:99:31
   |
99 |             let profile = cfg.get_profile();
   |                               ^^^^^^^^^^^ method not found in `Config`

error: aborting due to previous error
```

I am not yet sure why this is happening but it went away with a lot of `cargo clean` and `cargo update`.
However I realised two things while working on it:

- the source code in this repo does not seem to watch the release `0.3.0+688fc5c` on crates.io
- the code calls the method `get_profile()` on `Config` which has only been available since `cmake` version `0.1.45` so I think the `cmake` `version` field in `Cargo.toml` should be `0.1.45` insted of `0.1`. I am thinking the error above is because a wrong version of `cmake` was chosen in my dependency tree but not 100% sure.

**Comment by BusyJay** [comment]
Sorry, I did forget to push local changes. Now it should be synced with the crates.io.

`cargo update -p cmake` should solve the issue.

**Comment by hug-dev** [comment]
Great, thanks 👍
